# Generated by Django 5.0.3 on 2024-03-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_image_category_likes_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
